import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./components/theme";
import Navbar from "./components/Navbar";
import OfferRequest from "./components/OfferRequest";

export const metadata: Metadata = {
    title: "Пластиковые окна в Туле от производителя!",
    // description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <AppRouterCacheProvider>
                    <ThemeProvider theme={theme}>
                        <header>
                            <Navbar />
                        </header>
                        <main>{children}</main>
                        <footer>
                            <OfferRequest />
                        </footer>
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
